version: '2'

services:
  redis:
    image: 'redis:3.0-alpine'
    command: redis-server
    volumes:
      - 'redis:/data'
    ports:
    - '6379:6379'

  celery:
    build: .
    command: celery -A run.celery worker -l info
    volumes:
      - '.:/app'

  celery-beat:
     build: .
     command: celery -A run.celery beat -l info
     volumes:
       - '.:/app'

volumes:
  redis:

